TUTORIAL: Add "vatin" to standard fields
invoice-x/invoice2data pull request #524
Opened 2023-09-02 09:02 UTC by rmilecki

```
In most countries end customers pay a VAT (value-added tax). Companies
issuing invoices with VAT need to have a unique identification number
assigned. Local names and abbreviations of those numbers differ across
countries (UID, DIČ, CVR, CBL, NIP, NIF, etc.).

European Union seems to reference those numbers as "VAT identification
numbers". Some open projects like Wikipedia and OpenStreetMap use
"vatin" abbreviation for it. Add field of the same name to the TUTORIAL.
```

2023-09-02 09:02 UTC, rmilecki commented
* https://en.wikipedia.org/wiki/Value-added_tax
* https://wiki.openstreetmap.org/wiki/Key:ref:vatin

2023-09-02 12:18 UTC, bosd commented
Thanks for this PR.
Yet, currently the name `vat` is in use for this purpose.
At least in the templates contributed by me and alexis-via.

We use this number as the first method of matching the parsed invoice with the partner in the accounting software.

It appears this is one of the undocumented items of this module.
Is it ok to use the name `vat`?

2023-09-02 12:28 UTC, bosd commented
On a invoice there are generally 2 VAT numbers as required by law of some EU countries.
One is the vat number of the issuer, the other is of the receipient.

For the recipient vat number we use:

 fieldname | type | Description |
| -------------- | :---------: | :-------------------------------------- |
 company_vat | char | The vat number of the company to which the invoice is addressed to. Used to check if the invoice is actually is adressed to the company which wants to process it. (Very useful in multi-company setup)  |

2023-10-07 09:45 UTC, bosd requested changes

2023-10-07 09:45 UTC, bosd commented on TUTORIAL.md
> +- `vatin`: [VAT identification number](https://en.wikipedia.org/wiki/VAT_identification_number)
```suggestion
- `vat`: [VAT identification number](https://en.wikipedia.org/wiki/VAT_identification_number)
```

2023-10-31 21:47 UTC, bosd commented
Ping @rmilecki

2023-11-04 18:48 UTC, bosd approved these changes
Changed the field to `vat` as used in majority of templates.

2023-11-04 18:49 UTC, merged